### PR TITLE
Add manual installation instructions

### PR DESCRIPTION
**Pull request by phrozen77**
Added manual installation instructions (via ESPHome-Flasher) and one screenshot of a successful flash.

### CODE REVIEW

**Comment by DTTerastar** [comment]
Thanks!

**Comment by phrozen77** [comment]
You're welcome!

However, it seems the display of the pictures is a bit wonky on the live site whereas it seems to be just fine when in "Preview" mode? :(

**Comment by DTTerastar** [comment]
Yeah, image floats aren't the greatest... We need some css wizards to help us.

**Comment by DTTerastar** [comment]
Ok, I figured it out and made the website a bit wider so it now looks good.

**Comment by phrozen77** [comment]
The images now seem to be placed right, however now all the installation instructions under 1.2 and 2 are on one line on the live site..

**Comment by DTTerastar** [comment]
OMG, How did I not see that.  Was too worried about the images... It's fixed now.

**Pull request merged**
