### PR TITLE
Update home_assistant.md

### PR DESCRIPTION
**Pull request by hellcry37**
updated to new config required by changes in ha

### CODE REVIEW

**Review by hellcry37 — COMMENTED** [review]
edited comments

**Review by DTTerastar — APPROVED** [review]
Awesome!

**Review by UltraSalem — COMMENTED** [review]
there's a mix of single quotes and double quotes used on different strings - what is the correct standard? and sometimes the state topic string is inside quotes, and sometimes not? From here https://yaml.org/spec/1.2.2/ it seems all of them are valid, if they don't break due to special characters (so quotes preferred if there's a : in the text so you know it's not a key). Does Home Assistant have a style guide to set a preference?

**Comment by DTTerastar** [comment]
yaml is real wishy washy that way.  

I'm planning on getting hass discovery working for devices so we don't need to do any of this manual crap!  Soon...

**Pull request merged**
